Add installation for unzip(1).

diff --git a/downloader b/downloader
--- a/downloader
+++ b/downloader
@@ -50,7 +50,7 @@ echo "install $INSTALLER temporarily."
 echo "clone $REPO"
         git clone https://github.com/leorge/$REPO.git
         pushd $REPO && bash $myName && popd && rm $0
-    else
+    elif $INSTALLER unzip; then
 echo "download zip file"
         pushd $TMP
             ZIP=master.zip; rm -f $ZIP
@@ -59,5 +59,9 @@ echo "download zip file"
             cd $REPO
             CopyCmd
         popd
+    else
+        ERR=$?
+        echo "You can't install git and unzip" >&2
+        exit $ERR
     fi
 fi
